### ISSUE TITLE
[BUG] Warning raised in console when overriding a plan

### ISSUE THREAD

**Issue by ansmonjol** [getlago/lago-front#515]
**Describe the bug**

When overriding a plan, once redirected to the "add plan drawer" (in customer view), MUI raises an error regarding data provided to the `Autocomplete` component.

**To Reproduce**
1. Go to customer list
2. Click on a customer
3. Click on "Add a plan"
4. Select a plan
5. Click on "Override"
6. Fill in the firm and submit
7. Check your console

**Expected behaviour**

No warning should be raised

**Screenshots**

<img width="625" alt="image" src="https://user-images.githubusercontent.com/5517077/198682157-fae54ced-fbfc-42ac-8d27-8a51f6f7bea1.png">

**Additional context**

Warning have been detected after [this PR](https://github.com/getlago/lago-front/pull/514) merge

**Comment by jacobfenger** [comment]
I am pretty new to MUI, but it seems that what is happening is the following:

1. Plan is duplicated via the overwrite button when adding a plan
2. The `<Autocomplete>` component is called multiple times when redirecting to the "Add a plan" page, but the new duplicated plan does not exist yet for some reason? This error then appears in console because it is trying to compare all the existing plans to the newly created one, but it cannot find the new one yet?

Console output when I output the `option` and `val` in `ComboBox.tsx` in the `isOptionEqualToValue` parameter:

```
>> Object { label: "test - (1241)", labelNode: {…}, value: "5da0c707-a2cb-4ccc-add2-f03c20c9117d", disabled: false }
 f0a0c146-eec5-417d-9e96-65ea336cdfd2 [ComboBox.tsx:131](webpack://lago-front/src/components/form/ComboBox/ComboBox.tsx) 
>> Object { label: "test - (2)", labelNode: {…}, value: "94023bb8-91e4-4f29-9bed-926b1ba047cf", disabled: false }
 f0a0c146-eec5-417d-9e96-65ea336cdfd2 [ComboBox.tsx:131](webpack://lago-front/src/components/form/ComboBox/ComboBox.tsx)
>> Object { label: "test - (3)", labelNode: {…}, value: "cef66351-f256-4e39-988f-51b53f637fab", disabled: false }
 f0a0c146-eec5-417d-9e96-65ea336cdfd2 [ComboBox.tsx:131](webpack://lago-front/src/components/form/ComboBox/ComboBox.tsx)
>> MUI: The value provided to Autocomplete is invalid.
None of the options match with `"f0a0c146-eec5-417d-9e96-65ea336cdfd2"`.
You can use the `isOptionEqualToValue` prop to customize the equality test.
```

I am still familiarizing myself with this FE so I am still thinking on how to suppress this error. I need to read MUI docs.

The PR merge mentioned above doesn't seem like it has anything to do with this error which is weird if it started happening after it was merged.

**Comment by ansmonjol** [comment]
This part of the app have been totally refactored. 
This issue is not relevant anymore. Closing
